/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stephensons_rocket.glb --typescript 
Author: Science Museum Group (https://sketchfab.com/sciencemuseum)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/stephensons-rocket-09d73611eeda4aa7a4f3643766b340da
Title: Stephenson's Rocket
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

export function LocomotiveModel(props: any) {
  const { nodes, materials } = useGLTF('/models/stephensons_rocket.glb') as any
  return (
    <group {...props} dispose={null}>
      <Center position={[0, 0.8, 0]}>
        <group position={[23.68, -64.635, 88.315]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.027}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.White} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.White} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.White} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.White} />
        </group>
      </Center>
    </group>
  )
}

useGLTF.preload('/models/stephensons_rocket.glb')
