/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/steam-engine.glb --typescript 
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/model-of-the-watt-steam-engine-with-animation-36e57c231b6546b7bdd19bf4dba8063d
Title: Model of the Watt Steam Engine with animation
*/

import React from 'react'
import { useGLTF, useAnimations, Center } from '@react-three/drei'

export function SteamEngineModel(props: any) {
  const group = React.useRef<any>(null)
  const { nodes, materials, animations } = useGLTF('/models/steam-engine.glb')
  const { actions } = useAnimations(animations, group)

  // Auto-play the first animation clip
  React.useEffect(() => {
    if (actions && Object.keys(actions).length > 0) {
      const firstAction = actions[Object.keys(actions)[0]];
      if (firstAction) {
        firstAction.play();
      }
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <Center>
        <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
          <group name="maszyna_parowa_animacjafbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="main" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Cylinder012" position={[4.455, 1.796, 26.615]} rotation={[0, -0.009, 0]}>
                    <mesh name="Cylinder012_Material_0" geometry={nodes.Cylinder012_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder008" position={[4.461, -0.083, 26.563]} rotation={[0, -1.123, 0]}>
                    <mesh name="Cylinder008_Material_0" geometry={nodes.Cylinder008_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder009" position={[4.461, -0.599, 26.563]} rotation={[0, -0.009, 0]}>
                    <mesh name="Cylinder009_Material_0" geometry={nodes.Cylinder009_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder018" position={[4.455, 1.54, 26.615]} rotation={[0, -0.009, 0]}>
                    <mesh name="Cylinder018_Material_0" geometry={nodes.Cylinder018_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder006" position={[5.78, -1.005, 25.517]} rotation={[0, -0.14, 0]}>
                    <mesh name="Cylinder006_Material_0" geometry={nodes.Cylinder006_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder002" position={[-0.78, -0.986, 34.855]} rotation={[-3.012, -1.555, 0.129]} scale={0.366}>
                    <mesh name="Cylinder002_Material002_0" geometry={nodes.Cylinder002_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Plane003" position={[-0.78, -0.997, 34.855]} rotation={[-Math.PI / 2, 0.002, 0.236]}>
                    <mesh name="Plane003_Material002_0" geometry={nodes.Plane003_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder007" position={[-6.654, -0.976, 67.827]} rotation={[-3.141, -0.074, 0.002]}>
                    <mesh name="Cylinder007_Material002_0" geometry={nodes.Cylinder007_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder057" position={[1.738, -0.817, 34.235]} rotation={[Math.PI / 2, 0, -0.001]} scale={0.062}>
                    <mesh name="Cylinder057_Material002_0" geometry={nodes.Cylinder057_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder106" position={[0.203, 0, -0.005]} rotation={[0, -0.006, 0]}>
                    <mesh name="Cylinder106_Material002_0" geometry={nodes.Cylinder106_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder085" position={[-1.821, -1.101, 25.882]} rotation={[0, -0.041, 0]}>
                    <mesh name="Cylinder085_Material003_0" geometry={nodes.Cylinder085_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="noga_r_dol007">
                    <mesh name="noga_r_dol007_Material004_0" geometry={nodes.noga_r_dol007_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cube017" position={[-5.776, -0.994, 34.288]} rotation={[0, -0.023, 0]}>
                    <mesh name="Cube017_Material005_0" geometry={nodes.Cube017_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder042" position={[-5.855, -0.994, 36.018]} rotation={[1.571, 0, 0.033]} scale={0.099}>
                    <mesh name="Cylinder042_Material005_0" geometry={nodes.Cylinder042_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder043" position={[-5.776, -0.994, 34.288]} rotation={[0, 0.28, 0]}>
                    <mesh name="Cylinder043_Material005_0" geometry={nodes.Cylinder043_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder045" position={[-3.296, -1.389, 33.567]} rotation={[0, -0.002, 0]}>
                    <mesh name="Cylinder045_Material005_0" geometry={nodes.Cylinder045_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder046" position={[-3.295, -0.995, 33.567]} rotation={[0, -0.002, 0]}>
                    <mesh name="Cylinder046_Material005_0" geometry={nodes.Cylinder046_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder047" position={[-5.776, -0.995, 34.288]}>
                    <mesh name="Cylinder047_Material005_0" geometry={nodes.Cylinder047_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder105" position={[-5.776, -0.994, 34.291]}>
                    <mesh name="Cylinder105_Material005_0" geometry={nodes.Cylinder105_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder050" position={[-3.295, -0.995, 34.458]}>
                    <mesh name="Cylinder050_Material005_0" geometry={nodes.Cylinder050_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder051" position={[-3.295, -0.994, 34.37]} scale={0.043}>
                    <mesh name="Cylinder051_Material005_0" geometry={nodes.Cylinder051_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder052" position={[-3.249, -0.995, 34.347]} rotation={[0, -1.571, 0]} scale={0.018}>
                    <mesh name="Cylinder052_Material005_0" geometry={nodes.Cylinder052_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder107" position={[-3.293, -0.817, 35.534]}>
                    <mesh name="Cylinder107_Material005_0" geometry={nodes.Cylinder107_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube018" position={[-3.293, -0.994, 34.408]} rotation={[0, -0.001, 0]}>
                    <mesh name="Cube018_Material005_0" geometry={nodes.Cube018_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder048" position={[-5.776, -0.994, 34.137]} scale={0.074}>
                    <mesh name="Cylinder048_Material005_0" geometry={nodes.Cylinder048_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder049" position={[-5.687, -0.995, 34.099]}>
                    <mesh name="Cylinder049_Material005_0" geometry={nodes.Cylinder049_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube019" position={[1.738, -0.994, 33.212]} rotation={[0, 0.006, 0]}>
                    <mesh name="Cube019_Material005_0" geometry={nodes.Cube019_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder053" position={[-9.516, -1.185, 0.074]}>
                    <mesh name="Cylinder053_Material005_0" geometry={nodes.Cylinder053_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder058" position={[1.739, -0.995, 33.215]}>
                    <mesh name="Cylinder058_Material005_0" geometry={nodes.Cylinder058_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder059" position={[1.739, -0.994, 33.123]} scale={0.043}>
                    <mesh name="Cylinder059_Material005_0" geometry={nodes.Cylinder059_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder061" position={[1.773, -0.994, 23.417]}>
                    <mesh name="Cylinder061_Material005_0" geometry={nodes.Cylinder061_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder108" position={[1.741, -0.817, 34.288]}>
                    <mesh name="Cylinder108_Material005_0" geometry={nodes.Cylinder108_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder082" position={[-2.032, -1.114, 35.138]}>
                    <mesh name="Cylinder082_Material005_0" geometry={nodes.Cylinder082_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder083" position={[-2.032, -1.101, 35.123]}>
                    <mesh name="Cylinder083_Material005_0" geometry={nodes.Cylinder083_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder084" position={[-2.024, -1.101, 27.012]} rotation={[0, -0.041, 0]}>
                    <mesh name="Cylinder084_Material005_0" geometry={nodes.Cylinder084_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder086" position={[-1.489, -1.101, 24.093]} rotation={[0, -0.041, 0]}>
                    <mesh name="Cylinder086_Material005_0" geometry={nodes.Cylinder086_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder054" position={[-11.995, -1.185, 4.402]}>
                    <mesh name="Cylinder054_Material005_0" geometry={nodes.Cylinder054_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder060" position={[1.784, -0.995, 33.101]}>
                    <mesh name="Cylinder060_Material005_0" geometry={nodes.Cylinder060_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder016" position={[4.455, 1.657, 26.615]} rotation={[0, -0.009, 0]}>
                    <mesh name="Cylinder016_Material006_0" geometry={nodes.Cylinder016_Material006_0.geometry} material={materials['Material.006']} />
                  </group>
                  <group name="Cylinder017" position={[4.455, 1.656, 26.615]} rotation={[0, -0.009, 0]}>
                    <mesh name="Cylinder017_Material006_0" geometry={nodes.Cylinder017_Material006_0.geometry} material={materials['Material.006']} />
                  </group>
                  <group name="top">
                    <mesh name="top_Material001_0" geometry={nodes.top_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="left_1">
                    <mesh name="left_1_Material001_0" geometry={nodes.left_1_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="right_3" position={[10.235, 0, 18.971]}>
                    <mesh name="right_3_Material001_0" geometry={nodes.right_3_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="middle_2" position={[0.483, 0, 18.659]}>
                    <mesh name="middle_2_Material001_0" geometry={nodes.middle_2_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="inside_1" position={[-5.667, 1.598, 16.592]}>
                    <mesh name="inside_1_Material001_0" geometry={nodes.inside_1_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="ramka" position={[0.507, 0, 16.451]}>
                    <mesh name="ramka_Material001_0" geometry={nodes.ramka_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="back">
                    <mesh name="back_Material001_0" geometry={nodes.back_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="noga_1" position={[-9.33, -3.438, 9.096]}>
                    <mesh name="noga_1_Material001_0" geometry={nodes.noga_1_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="noga_2" position={[-9.33, 3.325, 9.096]}>
                    <mesh name="noga_2_Material001_0" geometry={nodes.noga_2_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="noga_3" position={[10.615, 3.325, 9.096]}>
                    <mesh name="noga_3_Material001_0" geometry={nodes.noga_3_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="noga_4" position={[10.615, -3.679, 9.096]}>
                    <mesh name="noga_4_Material001_0" geometry={nodes.noga_4_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="belka_r" position={[10.772, 0, 15.192]}>
                    <mesh name="belka_r_Material001_0" geometry={nodes.belka_r_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="belka_r001" position={[-9.463, 0, 15.192]}>
                    <mesh name="belka_r001_Material001_0" geometry={nodes.belka_r001_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cube">
                    <mesh name="Cube_Material001_0" geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cube001" position={[0, 7.744, 0]}>
                    <mesh name="Cube001_Material001_0" geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cylinder100">
                    <mesh name="Cylinder100_Material001_0" geometry={nodes.Cylinder100_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cylinder101">
                    <mesh name="Cylinder101_Material001_0" geometry={nodes.Cylinder101_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cylinder102">
                    <mesh name="Cylinder102_Material001_0" geometry={nodes.Cylinder102_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cylinder103">
                    <mesh name="Cylinder103_Material001_0" geometry={nodes.Cylinder103_Material001_0.geometry} material={materials['Material.001']} />
                  </group>
                  <group name="Cube002">
                    <mesh name="Cube002_Material_0" geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cube003" position={[-9.516, -1.185, 0]}>
                    <mesh name="Cube003_Material_0" geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cube011">
                    <mesh name="Cube011_Material_0" geometry={nodes.Cube011_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="moga_r">
                    <mesh name="moga_r_Material_0" geometry={nodes.moga_r_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="moga_r001" position={[-7.095, -2.345, 22.711]}>
                    <mesh name="moga_r001_Material_0" geometry={nodes.moga_r001_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="noga_r_dol" position={[5.617, -2.847, 22.017]}>
                    <mesh name="noga_r_dol_Material_0" geometry={nodes.noga_r_dol_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="noga_r_dol001">
                    <mesh name="noga_r_dol001_Material_0" geometry={nodes.noga_r_dol001_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="noga_r_dol002" position={[-9.516, -1.185, 0]}>
                    <mesh name="noga_r_dol002_Material_0" geometry={nodes.noga_r_dol002_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cube008">
                    <mesh name="Cube008_Material_0" geometry={nodes.Cube008_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder004" position={[-0.788, -2.44, 34.486]}>
                    <mesh name="Cylinder004_Material_0" geometry={nodes.Cylinder004_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cube014">
                    <mesh name="Cube014_Material_0" geometry={nodes.Cube014_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder013">
                    <mesh name="Cylinder013_Material_0" geometry={nodes.Cylinder013_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Plane005">
                    <mesh name="Plane005_Material_0" geometry={nodes.Plane005_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder010" position={[4.461, 0.554, 26.563]}>
                    <mesh name="Cylinder010_Material_0" geometry={nodes.Cylinder010_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder011">
                    <mesh name="Cylinder011_Material_0" geometry={nodes.Cylinder011_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder" position={[-9.516, -1.185, 0]}>
                    <mesh name="Cylinder_Material002_0" geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder001">
                    <mesh name="Cylinder001_Material002_0" geometry={nodes.Cylinder001_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="gwiazda" position={[-7.486, -1.372, 24.691]} rotation={[0.48, Math.PI / 2, 0]} scale={0.142}>
                    <mesh name="gwiazda_Material002_0" geometry={nodes.gwiazda_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Plane" position={[-9.516, -1.185, 0]}>
                    <mesh name="Plane_Material002_0" geometry={nodes.Plane_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="srodek_gwiazda" position={[-7.634, -1.185, 0]}>
                    <mesh name="srodek_gwiazda_Material002_0" geometry={nodes.srodek_gwiazda_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube004" position={[-7.183, -2.429, 25.959]}>
                    <mesh name="Cube004_Material002_0" geometry={nodes.Cube004_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube006" position={[-0.723, -2.429, 25.959]}>
                    <mesh name="Cube006_Material002_0" geometry={nodes.Cube006_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder014" position={[4.459, 2.603, 26.566]}>
                    <mesh name="Cylinder014_Material002_0" geometry={nodes.Cylinder014_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder015" position={[-9.516, -1.185, 0]}>
                    <mesh name="Cylinder015_Material002_0" geometry={nodes.Cylinder015_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder019">
                    <mesh name="Cylinder019_Material002_0" geometry={nodes.Cylinder019_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="gwizada_ozdoba" position={[-7.486, -1.372, 24.691]}>
                    <mesh name="gwizada_ozdoba_Material002_0" geometry={nodes.gwizada_ozdoba_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder027" position={[1.769, -0.985, 22.329]}>
                    <mesh name="Cylinder027_Material002_0" geometry={nodes.Cylinder027_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder029" position={[-1.461, -0.981, 22.329]}>
                    <mesh name="Cylinder029_Material002_0" geometry={nodes.Cylinder029_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder031" position={[-3.307, -0.981, 22.326]}>
                    <mesh name="Cylinder031_Material002_0" geometry={nodes.Cylinder031_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder033" position={[-3.307, -0.981, 25.128]}>
                    <mesh name="Cylinder033_Material002_0" geometry={nodes.Cylinder033_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder035" position={[-5.795, -0.981, 22.326]}>
                    <mesh name="Cylinder035_Material002_0" geometry={nodes.Cylinder035_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder037" position={[-5.776, -0.981, 25.327]}>
                    <mesh name="Cylinder037_Material002_0" geometry={nodes.Cylinder037_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder038" position={[-5.776, -0.981, 25.614]}>
                    <mesh name="Cylinder038_Material002_0" geometry={nodes.Cylinder038_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder040" position={[-9.516, -1.185, 0]}>
                    <mesh name="Cylinder040_Material002_0" geometry={nodes.Cylinder040_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube009" position={[-7.156, -0.976, 30.046]}>
                    <mesh name="Cube009_Material002_0" geometry={nodes.Cube009_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder021">
                    <mesh name="Cylinder021_Material002_0" geometry={nodes.Cylinder021_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder022" position={[-7.156, -0.976, 29.966]} scale={0.033}>
                    <mesh name="Cylinder022_Material002_0" geometry={nodes.Cylinder022_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder023" position={[-7.156, -0.195, 30.045]}>
                    <mesh name="Cylinder023_Material002_0" geometry={nodes.Cylinder023_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube025" position={[-6.967, -2.608, 26.8]} scale={0.909}>
                    <mesh name="Cube025_Material002_0" geometry={nodes.Cube025_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube026">
                    <mesh name="Cube026_Material002_0" geometry={nodes.Cube026_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder089">
                    <mesh name="Cylinder089_Material002_0" geometry={nodes.Cylinder089_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Circle001" position={[-7.947, -1.066, 24.133]} rotation={[0, 1.571, 0]} scale={0.245}>
                    <mesh name="Circle001_Material002_0" geometry={nodes.Circle001_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube005">
                    <mesh name="Cube005_Material002_0" geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cube007" position={[-0.743, -2.489, 33.591]} scale={0.315}>
                    <mesh name="Cube007_Material002_0" geometry={nodes.Cube007_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder005" position={[-0.743, -2.47, 34.593]}>
                    <mesh name="Cylinder005_Material002_0" geometry={nodes.Cylinder005_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder104" position={[-0.78, -1.094, 34.855]}>
                    <mesh name="Cylinder104_Material002_0" geometry={nodes.Cylinder104_Material002_0.geometry} material={materials['Material.002']} />
                  </group>
                  <group name="Cylinder028" position={[1.769, -0.985, 23.131]}>
                    <mesh name="Cylinder028_Material003_0" geometry={nodes.Cylinder028_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="Cylinder030" position={[-1.461, -0.981, 23.116]}>
                    <mesh name="Cylinder030_Material003_0" geometry={nodes.Cylinder030_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="Cylinder032" position={[-3.307, -0.981, 24.345]}>
                    <mesh name="Cylinder032_Material003_0" geometry={nodes.Cylinder032_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="Cylinder036" position={[-5.776, -0.981, 24.345]}>
                    <mesh name="Cylinder036_Material003_0" geometry={nodes.Cylinder036_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="Cylinder039" position={[-5.776, -0.981, 27.899]}>
                    <mesh name="Cylinder039_Material003_0" geometry={nodes.Cylinder039_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="Cylinder055" position={[1.769, -0.985, 23.131]}>
                    <mesh name="Cylinder055_Material003_0" geometry={nodes.Cylinder055_Material003_0.geometry} material={materials['Material.003']} />
                  </group>
                  <group name="Cylinder090" position={[-10.697, -1.776, 0]}>
                    <mesh name="Cylinder090_Material004_0" geometry={nodes.Cylinder090_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder091" position={[-10.727, -0.551, 0]}>
                    <mesh name="Cylinder091_Material004_0" geometry={nodes.Cylinder091_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder092" position={[-9.533, -1.172, 0]}>
                    <mesh name="Cylinder092_Material004_0" geometry={nodes.Cylinder092_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder093" position={[-8.217, -1.776, 0]}>
                    <mesh name="Cylinder093_Material004_0" geometry={nodes.Cylinder093_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder094" position={[-8.247, -0.551, 0]}>
                    <mesh name="Cylinder094_Material004_0" geometry={nodes.Cylinder094_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder095" position={[-7.052, -1.172, 0]}>
                    <mesh name="Cylinder095_Material004_0" geometry={nodes.Cylinder095_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder096" position={[-10.697, -1.776, 3.524]}>
                    <mesh name="Cylinder096_Material004_0" geometry={nodes.Cylinder096_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder097" position={[-10.727, -0.551, 3.524]}>
                    <mesh name="Cylinder097_Material004_0" geometry={nodes.Cylinder097_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cylinder098" position={[-9.533, -1.172, 3.524]}>
                    <mesh name="Cylinder098_Material004_0" geometry={nodes.Cylinder098_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol003" position={[-9.516, -1.185, 0]}>
                    <mesh name="noga_r_dol003_Material004_0" geometry={nodes.noga_r_dol003_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol004">
                    <mesh name="noga_r_dol004_Material004_0" geometry={nodes.noga_r_dol004_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol005" position={[3.269, -1.185, 0]}>
                    <mesh name="noga_r_dol005_Material004_0" geometry={nodes.noga_r_dol005_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol006" position={[2.816, 0.781, -0.076]}>
                    <mesh name="noga_r_dol006_Material004_0" geometry={nodes.noga_r_dol006_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol008">
                    <mesh name="noga_r_dol008_Material004_0" geometry={nodes.noga_r_dol008_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol009">
                    <mesh name="noga_r_dol009_Material004_0" geometry={nodes.noga_r_dol009_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol010" position={[-0.593, -2.283, 35.138]}>
                    <mesh name="noga_r_dol010_Material004_0" geometry={nodes.noga_r_dol010_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol011" position={[-0.874, -2.283, 35.138]}>
                    <mesh name="noga_r_dol011_Material004_0" geometry={nodes.noga_r_dol011_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol014" position={[4.908, 2.447, 26.924]}>
                    <mesh name="noga_r_dol014_Material004_0" geometry={nodes.noga_r_dol014_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol015" position={[4.012, 2.447, 26.924]}>
                    <mesh name="noga_r_dol015_Material004_0" geometry={nodes.noga_r_dol015_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol016" position={[4.917, 0.462, 26.676]}>
                    <mesh name="noga_r_dol016_Material004_0" geometry={nodes.noga_r_dol016_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol017" position={[4.008, 0.458, 26.676]}>
                    <mesh name="noga_r_dol017_Material004_0" geometry={nodes.noga_r_dol017_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol012" position={[-6.824, -2.652, 27.04]}>
                    <mesh name="noga_r_dol012_Material004_0" geometry={nodes.noga_r_dol012_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="noga_r_dol013" position={[-6.994, -2.652, 27.04]}>
                    <mesh name="noga_r_dol013_Material004_0" geometry={nodes.noga_r_dol013_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cube012" position={[-9.516, -1.185, 0.034]}>
                    <mesh name="Cube012_Material004_0" geometry={nodes.Cube012_Material004_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Cube020" position={[-7.161, -0.976, 29.172]} scale={[0.335, 0.367, 0.379]}>
                    <mesh name="Cube020_Material005_0" geometry={nodes.Cube020_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder062" position={[-7.484, -0.733, 28.311]}>
                    <mesh name="Cylinder062_Material005_0" geometry={nodes.Cylinder062_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder063" position={[-7.484, -1.205, 28.311]}>
                    <mesh name="Cylinder063_Material005_0" geometry={nodes.Cylinder063_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder064" position={[-7.474, -0.974, 28.297]} rotation={[0, -1.571, 0]} scale={-0.059}>
                    <mesh name="Cylinder064_Material005_0" geometry={nodes.Cylinder064_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder065" position={[-9.516, -1.103, 0]}>
                    <mesh name="Cylinder065_Material005_0" geometry={nodes.Cylinder065_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder066" position={[-7.724, -0.817, 27.674]}>
                    <mesh name="Cylinder066_Material005_0" geometry={nodes.Cylinder066_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder067" position={[-8.065, -0.805, 27.674]}>
                    <mesh name="Cylinder067_Material005_0" geometry={nodes.Cylinder067_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder069" position={[-8.068, -1.127, 27.674]}>
                    <mesh name="Cylinder069_Material005_0" geometry={nodes.Cylinder069_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder074" position={[-9.516, -0.844, 0]}>
                    <mesh name="Cylinder074_Material005_0" geometry={nodes.Cylinder074_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder075" position={[-6.949, -0.976, 26.898]}>
                    <mesh name="Cylinder075_Material005_0" geometry={nodes.Cylinder075_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder024">
                    <mesh name="Cylinder024_Material005_0" geometry={nodes.Cylinder024_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder025">
                    <mesh name="Cylinder025_Material005_0" geometry={nodes.Cylinder025_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube023" position={[-7.161, -0.976, 29.538]} scale={[0.035, 0.038, 0.04]}>
                    <mesh name="Cube023_Material005_0" geometry={nodes.Cube023_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube021">
                    <mesh name="Cube021_Material005_0" geometry={nodes.Cube021_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube022" position={[-7.898, -0.974, 26.013]} scale={[0.128, 0.134, 0.128]}>
                    <mesh name="Cube022_Material005_0" geometry={nodes.Cube022_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder041" position={[-5.776, -0.981, 30.323]}>
                    <mesh name="Cylinder041_Material005_0" geometry={nodes.Cylinder041_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder070" position={[-8.026, -0.974, 26.013]} rotation={[0, 1.571, 0]} scale={0.117}>
                    <mesh name="Cylinder070_Material005_0" geometry={nodes.Cylinder070_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder071">
                    <mesh name="Cylinder071_Material005_0" geometry={nodes.Cylinder071_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder026" position={[-7.156, -1.777, 27.149]}>
                    <mesh name="Cylinder026_Material005_0" geometry={nodes.Cylinder026_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder076" position={[-7.156, -0.175, 27.52]}>
                    <mesh name="Cylinder076_Material005_0" geometry={nodes.Cylinder076_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder077" position={[-6.897, -0.174, 26.988]}>
                    <mesh name="Cylinder077_Material005_0" geometry={nodes.Cylinder077_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder078" position={[-7.206, -0.177, 27.196]}>
                    <mesh name="Cylinder078_Material005_0" geometry={nodes.Cylinder078_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder079" position={[-7.408, 1.148, 28.192]} rotation={[0, -1.401, 0]} scale={0.045}>
                    <mesh name="Cylinder079_Material005_0" geometry={nodes.Cylinder079_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder080" position={[-6.705, 1.015, 27.167]}>
                    <mesh name="Cylinder080_Material005_0" geometry={nodes.Cylinder080_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube010" position={[-2.834, 0.514, 25.247]} scale={[0.074, 0.091, 0.091]}>
                    <mesh name="Cube010_Material005_0" geometry={nodes.Cube010_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube013">
                    <mesh name="Cube013_Material005_0" geometry={nodes.Cube013_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder099" position={[-0.005, -1.025, 24.936]}>
                    <mesh name="Cylinder099_Material005_0" geometry={nodes.Cylinder099_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder056" position={[1.769, -0.985, 23.131]}>
                    <mesh name="Cylinder056_Material005_0" geometry={nodes.Cylinder056_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder088" position={[-9.559, -1.185, 0.027]}>
                    <mesh name="Cylinder088_Material005_0" geometry={nodes.Cylinder088_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder087" position={[-9.516, -1.242, 0.03]}>
                    <mesh name="Cylinder087_Material005_0" geometry={nodes.Cylinder087_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube016">
                    <mesh name="Cube016_Material005_0" geometry={nodes.Cube016_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder034" position={[-3.307, -0.981, 25.772]}>
                    <mesh name="Cylinder034_Material005_0" geometry={nodes.Cylinder034_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder068" position={[-7.72, -1.13, 27.674]} rotation={[0, 0, -0.153]}>
                    <mesh name="Cylinder068_Material005_0" geometry={nodes.Cylinder068_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder072" position={[-7.898, -1.346, 27.43]}>
                    <mesh name="Cylinder072_Material005_0" geometry={nodes.Cylinder072_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder073" position={[-7.898, -1.532, 27.43]}>
                    <mesh name="Cylinder073_Material005_0" geometry={nodes.Cylinder073_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cube024">
                    <mesh name="Cube024_Material005_0" geometry={nodes.Cube024_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder020" position={[-7.156, -0.976, 29.812]} scale={[0.14, 0.14, 0.011]}>
                    <mesh name="Cylinder020_Material005_0" geometry={nodes.Cylinder020_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Cylinder081">
                    <mesh name="Cylinder081_Material005_0" geometry={nodes.Cylinder081_Material005_0.geometry} material={materials['Material.005']} />
                  </group>
                  <group name="Plane002">
                    <mesh name="Plane002_Material006_0" geometry={nodes.Plane002_Material006_0.geometry} material={materials['Material.006']} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      </Center>
    </group>
  )
}

useGLTF.preload('/models/steam-engine.glb')
