export interface PartInfo {
  id: string;
  name: string;
  nameEn: string;
  short: string;
  shortEn: string;
  description: string;
  descriptionEn: string;
  labelPos: [number, number, number];
  accent: string;
  category: "block" | "rotating" | "valvetrain" | "fuel";
}

export const PARTS: PartInfo[] = [
  {
    id: "block",
    name: "Thân máy (Block)",
    nameEn: "Engine Block",
    short: "Thân gang chứa 4 xy-lanh",
    shortEn: "Cast-iron body with 4 cylinders",
    description: "Thân máy bằng gang đúc, chứa 4 xy-lanh thẳng hàng. Bên trong có các áo nước làm mát và đường dầu bôi trơn.",
    descriptionEn: "Cast-iron engine block with 4 inline cylinders. Contains water jackets for cooling and oil galleries for lubrication.",
    labelPos: [0, 1.0, 0],
    accent: "#3a3d42",
    category: "block",
  },
  {
    id: "pistons",
    name: "Pít-tông (x4)",
    nameEn: "Pistons (x4)",
    short: "Chuyển động tịnh tiến trong xy-lanh",
    shortEn: "Reciprocating inside cylinders",
    description: "Bốn pít-tông bằng hợp kim nhôm, mỗi cái có 3 vòng đạn (2 vòng khí + 1 vòng dầu). Chuyển động lên-xuống theo thứ tự nổ 1-3-4-2.",
    descriptionEn: "Four aluminum-alloy pistons, each with 3 rings (2 compression + 1 oil). Move up/down in firing order 1-3-4-2.",
    labelPos: [-0.7, 1.8, -0.7],
    accent: "#8a9aaa",
    category: "rotating",
  },
  {
    id: "crankshaft",
    name: "Trục khuỷu",
    nameEn: "Crankshaft",
    short: "Biến tịnh tiến thành chuyển động quay",
    shortEn: "Converts reciprocation to rotation",
    description: "Trục khuỷu thép rèn với 4 chốt khuỷu bố trí lệch nhau 180°, cân bằng lực quán tính. Chuyển đổi lực pít-tông thành mô-men xoắn.",
    descriptionEn: "Forged steel crankshaft with 4 crank throws at 180° intervals for balanced inertia. Converts piston force into torque.",
    labelPos: [0, 0.8, 1.4],
    accent: "#566578",
    category: "rotating",
  },
  {
    id: "conrods",
    name: "Thanh truyền (x4)",
    nameEn: "Connecting Rods (x4)",
    short: "Pít-tông → trục khuỷu",
    shortEn: "Pistons → crankshaft",
    description: "Bốn thanh truyền bằng thép rèn nối pít-tông với trục khuỷu. Đầu nhỏ (small end) nối với chốt pít-tông, đầu to (big end) nối với chốt khuỷu.",
    descriptionEn: "Four forged-steel connecting rods linking pistons to the crankshaft. Small end connects to wrist pin, big end to crank pin.",
    labelPos: [0.7, 1.4, 0],
    accent: "#8a9099",
    category: "rotating",
  },
  {
    id: "head",
    name: "Nắp máy (Cylinder Head)",
    nameEn: "Cylinder Head",
    short: "Đậy kín xy-lanh, chứa van và bugi",
    shortEn: "Seals cylinders, houses valves and plugs",
    description: "Nắp máy bằng hợp kim nhôm chứa 8 van (4 van nạp + 4 van xả), 4 bugi, và buồng đốt dạng mái vát (pent-roof).",
    descriptionEn: "Aluminum-alloy cylinder head housing 8 valves (4 intake + 4 exhaust), 4 spark plugs, and pent-roof combustion chambers.",
    labelPos: [0, 2.9, 0],
    accent: "#7a8898",
    category: "block",
  },
  {
    id: "valvetrain",
    name: "Cơ cấu van",
    nameEn: "Valvetrain",
    short: "Van nạp/xả, lò xo, cò mổ",
    shortEn: "Intake/exhaust valves, springs, rockers",
    description: "8 van nấm (poppet valve) bằng thép chịu nhiệt, mỗi xy-lanh có 1 van nạp + 1 van xả. Lò xo van đóng van khi cam không tác động.",
    descriptionEn: "8 heat-resistant steel poppet valves (1 intake + 1 exhaust per cylinder). Valve springs close valves when the cam is not actuating.",
    labelPos: [0.5, 2.6, -0.5],
    accent: "#8a9099",
    category: "valvetrain",
  },
  {
    id: "camshaft",
    name: "Trục cam",
    nameEn: "Camshaft",
    short: "Điều khiển đóng/mở van theo đúng nhịp",
    shortEn: "Controls valve timing",
    description: "Trục cam bằng thép tôi cứng, quay chậm hơn trục khuỷu 2 lần. Các vấu cam (lobe) có biên dạng đặc biệt để mở van nạp/xả đúng thời điểm.",
    descriptionEn: "Hardened steel camshaft rotating at half crankshaft speed. Cam lobes have special profiles to open intake/exhaust valves at precise timing.",
    labelPos: [0.5, 2.3, 1.3],
    accent: "#566578",
    category: "valvetrain",
  },
  {
    id: "timing-belt",
    name: "Dây đai cam / Timing Belt",
    nameEn: "Timing Belt",
    short: "Đồng bộ trục cam với trục khuỷu",
    shortEn: "Synchronizes camshaft with crankshaft",
    description: "Dây đai răng bằng cao su cốt thép, kết nối bánh răng trục khuỷu với bánh răng trục cam. Đảm bảo trục cam quay đúng 1/2 tốc độ trục khuỷu.",
    descriptionEn: "Reinforced rubber timing belt connecting the crankshaft sprocket to the camshaft sprocket. Ensures the camshaft runs at 1/2 crankshaft speed.",
    labelPos: [-0.5, 3.0, 1.0],
    accent: "#1a1512",
    category: "valvetrain",
  },
  {
    id: "spark-plugs",
    name: "Bugi (x4)",
    nameEn: "Spark Plugs (x4)",
    short: "Đánh lửa đốt cháy hỗn hợp nhiên liệu",
    shortEn: "Ignite the air-fuel mixture",
    description: "Bốn bugi, mỗi xy-lanh một cái. Điện cực trung tâm bằng đồng, vỏ cách điện bằng sứ. Đánh lửa đúng thời điểm cuối kỳ nén.",
    descriptionEn: "Four spark plugs, one per cylinder. Copper center electrode, ceramic insulator. Fire at the end of the compression stroke.",
    labelPos: [0, 3.1, -0.5],
    accent: "#f0ecd6",
    category: "fuel",
  },
  {
    id: "intake-manifold",
    name: "Ống nạp",
    nameEn: "Intake Manifold",
    short: "Dẫn không khí/nhiên liệu vào xy-lanh",
    shortEn: "Delivers air/fuel to cylinders",
    description: "Ống nạp bằng hợp kim nhôm chia 4 nhánh đều đến từng xy-lanh. Đầu vào có họng ga (throttle body).",
    descriptionEn: "Aluminum intake manifold with 4 equal-length runners to each cylinder. Throttle body at the inlet.",
    labelPos: [-1.5, 1.8, 0],
    accent: "#7a8898",
    category: "fuel",
  },
  {
    id: "exhaust-manifold",
    name: "Ống xả",
    nameEn: "Exhaust Manifold",
    short: "Thu khí xả từ xy-lanh",
    shortEn: "Collects exhaust gases from cylinders",
    description: "Ống xả bằng gang đúc hoặc thép không gỉ, gom khí xả từ 4 xy-lanh vào một đường ống chung xuống bộ xử lý khí thải.",
    descriptionEn: "Cast-iron or stainless steel exhaust manifold collecting exhaust gases from all 4 cylinders into a single downpipe.",
    labelPos: [1.5, 1.8, 0],
    accent: "#3a3d42",
    category: "fuel",
  },
  {
    id: "flywheel",
    name: "Bánh đà",
    nameEn: "Flywheel",
    short: "Quán tính giữ đều tốc độ",
    shortEn: "Inertia smooths the rotation",
    description: "Bánh đà lớn tích lũy động năng, giữ trục khuỷu quay đều giữa các kỳ nổ. Vành ngoài có răng cho máy khởi động.",
    descriptionEn: "Large flywheel stores kinetic energy, smoothing crankshaft rotation between power strokes. Outer ring gear for the starter motor.",
    labelPos: [1.8, 1.2, 1.4],
    accent: "#3a3d42",
    category: "rotating",
  },
  {
    id: "oil-pan",
    name: "Các te dầu",
    nameEn: "Oil Pan",
    short: "Chứa dầu bôi trơn dưới đáy máy",
    shortEn: "Holds engine oil at the bottom",
    description: "Các te dầu bằng thép dập chứa 4-5 lít dầu bôi trơn, có vách ngăn chống xoáy để đảm bảo bơi dầu luôn ngập trong dầu.",
    descriptionEn: "Stamped steel oil pan holding 4-5 liters of engine oil, with baffles to prevent starvation during cornering.",
    labelPos: [0, 0.0, 0],
    accent: "#8a9099",
    category: "block",
  },
];

export const PART_MAP: Record<string, PartInfo> = Object.fromEntries(
  PARTS.map((p) => [p.id, p]),
);
